name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - cd DraftCleaner
    - run: npm install
    - run: npm test
    - cd ../GANReviewTool
    - run: npm install
    - run: npm test
    - cd ../NotSoFast
    - run: npm install
    - run: npm test
    - cd ../SpeciesHelper
    - run: npm install
    - run: npm test
    - cd ../UserRightsDiff
    - run: npm install
    - run: npm test
