name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - working-directory: ./DraftCleaner
      run: npm install
    - working-directory: ./DraftCleaner
      run: npm test

    - working-directory: ./GANReviewTool
      run: npm install
    - working-directory: ./GANReviewTool
      run: npm test

    - working-directory: ./NotSoFast
      run: npm install
    - working-directory: ./NotSoFast
      run: npm test

    - working-directory: ./SpeciesHelper
      run: npm install
    - working-directory: ./SpeciesHelper
      run: npm test
    
    - working-directory: ./UserRightsDiff
      run: npm install
    - working-directory: ./UserRightsDiff
      run: npm test